version: 0.2

env:
  parameter-store:
    AWS_REGION: "/vumi/aws-region"
    ECR_REPOSITORY_URL: "/vumi/ecr-repo-url"
    PROJECT_NAME: "/vumi/project_name"
    DB_TYPE: "/vumi/db_type"
    DB_HOST: "/vumi/db_host"
    DB_NAME: "/vumi/db_name"
    DB_USER: "/vumi/db_user"
    DB_PASS: "/vumi/db_pass"
    DB_PORT: "/vumi/db_port"
    APP_PORT: "/vumi/app_port"
    WWW_ROOT: "/vumi/www_root"
    FRONTEND_PORT: "/vumi/frontend_port"
    DOCKER_USERNAME: "/vumi/docker-hub-username"
    DOCKER_PASSWORD: "/vumi/docker-hub-password"
    SSM_AUTOMATION_DOCUMENT_NAME: "/vumi/automation-document-name"
    SSM_AUTOMATION_ROLE_ARN: "/vumi/automation-role-arn"
    ASG_NAME: "/vumi/asg-name"

phases:
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
      - echo Logging in to Amazon ECR...
      - echo $AWS_REGION $ECR_REPOSITORY_URL
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPOSITORY_URL

  build:
    commands:
      - echo Building Docker image for app Service on port $APP_PORT...
      # - docker build --build-arg app_port=$APP_PORT -t app .
      # - docker tag app:latest $ECR_REPOSITORY_URL/vumi/app:v1
      # - docker push $ECR_REPOSITORY_URL/vumi/app:v1

      - echo Building Docker image for frontend Service on port $FRONTEND_PORT...
      # - docker build --build-arg app_port=$FRONTEND_PORT -t frontend ./frontend
      # - docker tag frontend:latest $ECR_REPOSITORY_URL/vumi/frontend:v1
      # - docker push $ECR_REPOSITORY_URL/vumi/frontend:v1

  post_build:
    commands:
      - echo "Starting SSM automation execution..."
      - aws ssm start-automation-execution --document-name $SSM_AUTOMATION_DOCUMENT_NAME --document-version "\$DEFAULT" --parameters {"AutomationAssumeRole":[$SSM_AUTOMATION_ROLE_ARN],"ASGName":["$ASG_NAME"]} --region $AWS_REGION
