version: "3.7"
services:
  app:
    image: 058264454514.dkr.ecr.ap-southeast-1.amazonaws.com/vumi/app
    ports: 
      - "8044:8044"
    container_name: vumi_prod_moodle4
    network_mode: host
    volumes:
      - ./moodle400:/var/www/html
      - ./moodledata:/var/www/moodledata:rw
    restart: always
  froentend:
    image: 058264454514.dkr.ecr.ap-southeast-1.amazonaws.com/vumi/frontend
    container_name: vumi_prod_frontend
    ports: "4244:4244"
    network_mode: host
    restart: always
