version: "3.7"
services:
  app:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - app_port=${APP_PORT}
    
    container_name: ${PROJECT_NAME}_moodle4_local
    ports:
      - "8044:8044"
    # network_mode: host
    # volumes:
    #   - ./moodle400:/var/www/html
    #   - ./moodledata:/var/www/moodledata:rw
    restart: always
  froentend:
    env_file:
      - .env
    build:
      context: frontend
      dockerfile: Dockerfile
      args:
        - frontend_port=${FRONTEND_PORT}
    container_name: ${PROJECT_NAME}_frontend_local
    ports:
      - "4244:80"
    # network_mode: host
    restart: always
